### ISSUE TITLE
Symbol © in a ANSI encoded file throws an error

### ISSUE THREAD

**Issue by derpynirvash** [xiagu/jekyll-rp-logs#13]
Due to whatever weird encoding is done, a symbol like © or ™ that is in a log file encoded with ANSI will result in the error below.

Error reading file /_rps/test.md: invalid byte sequence in UTF-8
  Liquid Exception: invalid byte sequence in UTF-8 in _rps/test.md
jekyll 2.5.3 | Error:  invalid byte sequence in UTF-8

Only happens if the symbol is in a emote or text line.

Switching to UTF-8 encoding fixes this issue, but it is still odd enough to be worth noting. 
This has been tested in the latest build and in an old build before jekyll-rp_logs moved to a gem.

**Comment by irisfofs** [comment]
That's odd that it assumes the files are UTF-8 rather than reading the encoding. It might be a more underlying issue with Jekyll or Liquid.

**Comment by derpynirvash** [comment]
Just a note, as of version 2.0 jekyll assumes an encoding of UTF-8

> Encoding
> Set the encoding of files by name. Only available for Ruby 1.9 or later). The default value is utf-8  starting in 2.0.0, and nil before 2.0.0, which will yield the Ruby default of ASCII-8BIT. Available encodings can be shown by the command ruby -e 'puts Encoding::list.join("\n")'.
> encoding: ENCODING

http://jekyllrb.com/docs/configuration/
https://github.com/jekyll/jekyll/issues/2029

**Comment by derpynirvash** [comment]
So yea, not a bug in the plugin, but with jekyll itself!
