### ISSUE TITLE
Add Tag Aliases

### ISSUE THREAD

**Issue by tecknojock** [xiagu/jekyll-rp-logs#36]
The ability to make one tag become another tag to help homogenize tags that may be all the same thing, put different ways.

**Comment by irisfofs** [comment]
This is a useful feature on an imageboard where things are tagged by multiple people, but here one person (theoretically) is handling all the tagging. Why not just standardize your tags yourself?

**Comment by tecknojock** [comment]
Because then you have to go back and consult wether you tagged things tatzl pony or tazlpony or any number of other things with multiple perfectly viable options. Since there is no autocompletion, since tagging is done in a txt file, this is the next best thing.

**Comment by irisfofs** [comment]
That's what "find/replace in files" is for? 

I just object to adding another layer of tag shenanigans (that the user has to manage themselves) on top of the existing infrastructure. Will maybe consider it, but simplicity is one of the main goals here.

**Comment by tecknojock** [comment]
Sure, find/replace in files is fine when you've just uploaded a bunch of logs, but when you're adding new logs, one or two at a time you're forcing the user to have to look up what tags they have used already and homogenize them, unless you're suggesting the user write their own find/replace script to look for those variations and homogenize them? But then that would be something that seems like it should be under this scope.

And on top of that, its not something the user /has/ to manage. They could certainly ignore the feature all together. You could give the same exact argument to tag implications, which you seemed receptive to before.
