### ISSUE TITLE
Custom Ordering of RPs

### ISSUE THREAD

**Issue by tecknojock** [xiagu/jekyll-rp-logs#43]
It'd be neat if, at least for canon or Arc stuff you could do a manual ordering of RPs if things happen out of order. Perhaps A flag that allows for manual sorting via decimal values.

**Comment by irisfofs** [comment]
You can already sort inside arcs with the `time_line` option. You can give the RP a fake start date that it gets sorted by instead of its real one.

**Comment by tecknojock** [comment]
Can you alter the start date in a flag? Or do you have to find/replace the date to an earlier date?

**Comment by irisfofs** [comment]
Why would you want to use a flag for it? You can just set the `start_date` in the YAML front matter at the top of the file.

Also, that's what `time_line` does, it is... a separate `start_date` I guess. For sorting only.

**Comment by tecknojock** [comment]
by flag i meant yaml xP

**Comment by tecknojock** [comment]
Time_line does this, I shoulda closed :P
