### ISSUE TITLE
Support for User Scripts/plugins

### ISSUE THREAD

**Issue by tecknojock** [xiagu/jekyll-rp-logs#44]
It would be nice if the user had the ability to inject scripts into the build sequence without having to modify any files in the project.

**Comment by irisfofs** [comment]
You kind of already can. You can still write other plugins for Jekyll and put them in the `./plugins` directory, and Jekyll will pick them up and run them.

In the extreme case you can even monkeypatch this plugin:

``` ruby
module Jekyll
  module RpLogs
    def initialize(config)
      # Should actually probably complain if things are undefined or missing
      config["rp_convert"] = true unless config.key? "rp_convert"

      RpLogGenerator.extract_settings(config)
      LogLine.extract_settings(config)

      Jekyll.logger.info "Loaded jekyll-rp_logs #{RpLogs::VERSION}"

      puts "Ha ha I'm redefining this method"
    end
  end
end
```

**Comment by tecknojock** [comment]
oh huh, neat
