### ISSUE TITLE
Individual RP Stats

### ISSUE THREAD

**Issue by tecknojock** [xiagu/jekyll-rp-logs#51]
I'd be nice to get a count of posts, words, Average character count per RPer, Time spent, and number of RP sessions.

**Comment by irisfofs** [comment]
Duplicate of #34

**Comment by tecknojock** [comment]
This is not a duplicate I dont think. That one is aggregate for the site is it not?

**Comment by irisfofs** [comment]
Perhaps the additional details have just been in my head, then, but I'd intended similar statistics available per-page as well.
