### ISSUE TITLE
Summary or description field for RPs

### ISSUE THREAD

**Issue by derpynirvash** [xiagu/jekyll-rp-logs#54]
It would be helpful to have a summary field that would appear at the top of a RP page, and/or appear as alt text/title text for the link to the RP from the main page.

Can be used as a 'tldr' for long story related RPs.

**Comment by tecknojock** [comment]
https://github.com/xiagu/jekyll-rp_logs/pull/78/commits/d979f079ab415ee74ef74d732093b7ef6129e74b closes out this issue.
